dist: trusty
sudo: true

language: python

jobs:
  include:
    - python: 3.6
    # - <<: *xenial-mixin
    - python: nightly

# .mixins:
# - &xenial-mixin
#   dist: xenial
#   sudo: true
#   addons:
#     apt:
#       packages:
#         - libgnutls-dev

matrix:
  allow_failures:
    - python: nightly

install:
    - ./bootstrap.sh

script:
    - inv lint
    - inv test --cov

after_success:
    - codecov
